name: Frontend Task
description: Use this form to describe a frontend task
title: "[FE] "
labels: [frontend]
assignees:
  - carnophager
body:
  - type: markdown
    attributes:
      value: |
        ## 🛠️ Frontend Task

  - type: input
    id: summary
    attributes:
      label: Task Summary
      description: A one-line summary of the task
      placeholder: e.g., Implement responsive navbar
    validations:
      required: true

  - type: input
    id: original_estimate
    attributes:
      label: ⏱️ Original Time Estimate
      description: Estimated time to complete the task (e.g., 4h, 1d)
      placeholder: e.g., 4h
    validations:
      required: false

  - type: input
    id: actual_time
    attributes:
      label: ⌛ Actual Time Spent
      description: How much time was actually spent (fill after completion)
      placeholder: e.g., 6h
    validations:
      required: false

  - type: textarea
    id: details
    attributes:
      label: Detailed Description
      description: What needs to be implemented, changed, or improved?
      placeholder: e.g., Add mobile-first responsive logic, toggle menu on small screens

  - type: textarea
    id: screens
    attributes:
      label: Screens / Components Affected
      description: List relevant files or components
      placeholder: e.g., Header.tsx, NavBar.tsx

  - type: input
    id: design
    attributes:
      label: Design Reference
      description: Figma or screenshot link
      placeholder: e.g., https://www.figma.com/file/...

  - type: checkboxes
    id: acceptance
    attributes:
      label: ✅ Acceptance Criteria
      options:
        - label: Matches design
        - label: Works on all breakpoints
        - label: Reusable code
        - label: Tested in major browsers

  - type: textarea
    id: tech_notes
    attributes:
      label: Technical Notes
      description: Add implementation tips, dependencies, or constraints
      placeholder: Use Tailwind; reuse ToggleMenu component from utils

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Anything else?
